name: constraint_solver
description: A starting point for Dart libraries or applications.
version: 1.0.0
#repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  # TODO: Add dependencies
dev_dependencies:
  checks: ^0.2.0
  lints: ^2.0.0
  intl: ^0.17.0
  test: ^1.21.0
